### PR TITLE
update flutter_map dep to support v7

### PR DESCRIPTION
**Pull request by timkandel**

### CODE REVIEW

**Comment by timkandel** [comment]
There are no changes required to support flutter_map 7.0 as far as I can tell, and a quick test in one of my apps worked without any problems

**Comment by ibrierley** [comment]
Thanks for this. I note, on testing https://github.com/ibrierley/flutter_map_dragmarker/pull/39 has introduced a bug that wasn't caught... On dragging the bottom marker in test example, at screen edge (testing on web), I note it moves twice as fast (roughly), as it should..not sure if this could/should be fixed before going to v7 proper on pub...

**Comment by timkandel** [comment]
Hey, I have just tested for this bug on both my change as well as on 99d2034 (the commit before the PR that introduced this bug). For me the bottom marker moves faster in Chrome on both commits. However this is not consistent, it appears to randomly change. Sometimes on marker is "slow", sometimes both are and sometimes both are "fast". Not sure if this is related to the DragMarker implementation or some other changes.

**Comment by timur-harin** [comment]
@ibrierley 
Please check and start support flutter_map 7.0.x 
I really like and use your plugin!

**Comment by ibrierley** [comment]
@timkandel thanks for the feedback. Out of interest, if you change the callback timeout from 10 to 20ms, eg in _pan,
line 149 I think to ```const Duration(milliseconds: 20),``` does that help with the moving marker near edge problem ?

I can't remember how I came up with the original figure tbh, but 20 helps on mine, but I'm wondering if it varies per device...

**Comment by timur-harin** [comment]
@ibrierley 
please update version for pub.dev

**Comment by ibrierley** [comment]
Can you test the latest version I've just updated...I've tested on web and there's a couple of deprecation warnings, but if I fix those, other errors come along, so tempted to leave that for the moment. Maybe test on a mobile, as I don't have full access to test that atm. If all looks ok to you, I'll update to pub.dev

**Comment by timkandel** [comment]
> @timkandel thanks for the feedback. Out of interest, if you change the callback timeout from 10 to 20ms, eg in _pan, line 149 I think to `const Duration(milliseconds: 20),` does that help with the moving marker near edge problem ?
> 
> I can't remember how I came up with the original figure tbh, but 20 helps on mine, but I'm wondering if it varies per device...

> Can you test the latest version I've just updated...I've tested on web and there's a couple of deprecation warnings, but if I fix those, other errors come along, so tempted to leave that for the moment. Maybe test on a mobile, as I don't have full access to test that atm. If all looks ok to you, I'll update to pub.dev

@ibrierley sorry for the late response. I could actually reproduce the problem you described on one of my Android emulators now. Changing the delay to 20ms does indeed improve the behavior, so the latest version appears to be working well 👍

**Pull request merged**
