### PR TITLE
Bump dependency to flutter_map 1.0.0

### PR DESCRIPTION
**Pull request by pablojimpas**
Fixes breaking changes introduced since the last major flutter_map
release. Primarily instances of Stream<Null> used in the plugin API now
have become Stream<void>.

While I was here I've also added an analysis_options.yaml file using
flutter_lints and fix some static analysis errors found, hopefully I
didn't break something. I've also improved a little bit the formatting
and wording of the REAME, mostly cosmetic changes.

To release a new version bump it in the pubspec.yaml and update the
changelog when it's ready.

### CODE REVIEW

**Review by ibrierley — COMMENTED** [review]
Thanks for this! There's 2 bits that may be an issue...
Removing 
flutter: 
  uses-material-design: true
from the main pubspec breaks the icons from working which is curious, as I thought they'd just be needed in the example pubspec.

I'd also rather the pubspec.lock not be included unless there's a compelling reason. The prevailing wisdom is not to include this for packages, but include for applications, to allow a wider scope of versions to be used.

**Comment by ibrierley** [comment]
Actually, I guess we should also bump the version of this package...

**Review by ibrierley — COMMENTED** [review]
I think this is still just waiting for the material design to be back in the main pubspec, but otherwise all looks good.

**Comment by pablojimpas** [comment]
> I think this is still just waiting for the material design to be back in the main pubspec, but otherwise all looks good.

Ready now! Sorry again...

**Comment by ibrierley** [comment]
lgtm thanks!

**Pull request merged**
