### PR TITLE
Partial rewrite

### PR DESCRIPTION
**Pull request by josxha**
This pull request adds the following changes:
- performance improvments
- add documentation
- merge builder and feedbackBuilder
- removed the use of ValueKeys because of potential side effects
- add native implementations to the example project
- update README.md
- fix issues when the scrollMapNearEdge (previously updateMapNearEdge) feature

Please note that this pr introduces breaking changes.

### CODE REVIEW

**Comment by ibrierley** [comment]
I'll try and get chance to test tomorrow. What are the real benefits of all of the extra files, just it seems that a couple of methods in a few files has turned into 127 modified files :) ?

**Comment by josxha** [comment]
127 files sounds like a lot.😅 But most of the files got created by the `flutter create` command.
As @pablojimpas wrote:
> Having a folder for each specific platform allows anyone to just execute flutter run to launch the example app instead of recreating the project first with flutter create . and overall brings a faster development cycle for contributors since they can test their changes directly. I doubt that it creates a lot of maintenance effort, since those platform-specific files are only created once and rarely touched again (unless you're actually building a real production app).

I can agree on his statement. It's much easier to try out a package or do some testing or contribution if there is already a complete example project included. You would have to create them locally anyways so why not push them.

Additionally, I split the package files itself into a seperate file for each class. All logic is now located under `/src` and gets exported by `dragmarkers.dart`. This is a good practice to define what class can be publicly accessed.

---

Btw @pablojimpas, if you like, you're welcome to do some testing for this pull request too. (:

**Comment by pablojimpas** [comment]
> Btw @pablojimpas, if you like, you're welcome to do some testing for this pull request too. (:

I'm on it! Don't worry about all the new files @ibrierley, they will almost certainly never be touched again, there's no need to review them either.



> Additionally, I split the package files itself into a seperate file for each class. All logic is now located under `/src` and gets exported by `dragmarkers.dart`. This is a good practice to define what class can be publicly accessed.

Indeed, this is a good practice, furthermore, most packages in the ecosystem follow the convention of naming the library that they declare and the file that gets exposed the same as the package itself. For example, [`flutter_map`](https://github.com/fleaflet/flutter_map/blob/master/lib/flutter_map.dart), so that the users of the package can import it intuitively:

```dart
// Instead of this:
import 'package:flutter_map_dragmarker/dragmarker.dart';
// Prefer this:
import 'package:flutter_map_dragmarker/flutter_map_dragmarker.dart';
```

**Comment by josxha** [comment]
Sounds good to me, changed in https://github.com/ibrierley/flutter_map_dragmarker/pull/30/commits/af4c7cc920e84d67412c0d4567a8ef109f1b8884.

**Comment by ibrierley** [comment]
Thanks for the work on this. Couple of bits...main showstopper atm, is that on web or linux desktop, if you drag a marker with ```scrollMapNearEdge: true``` off the screen for whatever reason, it goes a bit strange. The screen continues panning for ever, and you can't seem to stop it (and intermediate drags are kinda wrong). I haven't got a mobile to test on atm to verify that, but I assume that doesn't have the same issue as you can't get outside of the screen iyswim.

There's a slight annoying thing every time I switch PRs I need to do a git clean  -d  -f . && flutter create ., but I think that's probably because the current master doesn't have those new o.s files, so assuming this is just a one off whilst transitioning, I'm all good with that.

Thanks for your work on this.

**Comment by pablojimpas** [comment]
> The screen continues panning for ever, and you can't seem to stop it (and intermediate drags are kinda wrong). I haven't got a mobile to test on atm to verify that, but I assume that doesn't have the same issue as you can't get outside of the screen iyswim.

I can confirm this issue from my testing and that it also happens on Android, it does not happen always though, it's hard to trigger but when it happens the whole app it's basically broken.

**Comment by josxha** [comment]
Well spotted! The problem was that the map layer removes the marker when outside of the map bounds. This prevents the marker to receive an `onVerticalDragEnd`/`onHorizontalDragEnd` event. 

My solution is that the timer checks itself if the marker is outside of the visible map bounds and cancel itself if not. That solved the issue.

**Comment by ibrierley** [comment]
Thanks for this, will try and get it tested later.

**Comment by ibrierley** [comment]
Thanks, I think that all works well now.

I think the only thing I'm a bit unsure of, I think with this change, if I drag the icons near the bottom of the icon, it doesn't drag the whole icon, but the map instead. I'm not sure if there is some offset now for it that's on by default, or if something else has changed ? Just makes it feel like you're missing it quite a lot when you're not (testing on linux and web)

To recreate, drag near the bottom of the marker doesn't work. Drag near the hole inside the marker and above works fine. I've tried removing the offset on the markers, but didn't seem to make any difference.

**Comment by josxha** [comment]
@ibrierley Yes, you're right. It's indeed offset. The Problem is that the width and height of the `Positioned` widget defaults to 30. If the child `Icon` is bigger a part of it it gets displayed outside of the `Positioned` widget. 
I don't think that this behaviour gets introduced by this pr but i can try to fix it.
image

**Comment by josxha** [comment]
This problem doesn't occures if the Positioned widget is big enough, so the fix was to set the marker size to the biggest widget size (when it gets dragged aroun).

There are two more things in my mind but I won't have currently the time to implement them:
- Use anchor point instead of size (height / width)
- Rotate the drag marker around the anchor point

**Comment by ibrierley** [comment]
Thanks for all your work on this, all tests good for me

**Pull request merged**
