### PR TITLE
Support for flutter_map 4.0.0

### PR DESCRIPTION
**Pull request by josxha**
This pull request adds support for flutter_map 4.0.0.

### CODE REVIEW

**Comment by ibrierley** [comment]
Thanks!

**Comment by josxha** [comment]
but...it was not ready, I marked it as draft. 😧

**Comment by ibrierley** [comment]
Hah, sorry I missed that, let me know when it's done.

**Comment by ibrierley** [comment]
bw this version isn't published on pub.dev, so I think it's fairly safe currently.

**Comment by josxha** [comment]
> bw this version isn't published on pub.dev, so I think it's fairly safe currently.

Yes I agree and it actually works well with this merge. But i'm going to add some more work (:

**Pull request merged**
